spring:
  application:
    name: demo-rag
  datasource:
    url: jdbc:postgresql://localhost:5432/vector
    username: postgres
    password: root
  ai:
    ollama:
      base-url: http://localhost:11434/
      embedding:
        options:
          model: nomic-embed-text
      chat:
        options:
          model: llama3.1